# Generated by Django 4.0.5 on 2022-07-19 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.CharField(max_length=30)),
                ('nacionalidad', models.CharField(choices=[('ecuatoriana', 'Ecuatoriana'), ('peruana', 'Peruana'), ('colombiana', 'Colombiana')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_departamento', models.IntegerField(verbose_name='costo departamento')),
                ('num_cuartos', models.IntegerField(verbose_name='numero de cuartos')),
                ('num_banos', models.IntegerField(verbose_name='numero de banos')),
                ('valor', models.IntegerField(verbose_name='valor alicuota')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='administrativo.propietario')),
            ],
        ),
    ]
